name: SRE bootcamp build

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch: 

jobs:
  build:
    runs-on: self-hosted
    steps:
        - name: Check out repo
          uses: actions/checkout@v3

        - name: Set up Python 3.10
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"
        
        - name: Install dependencies
          id: dependency
          run: |
            python -m pip install --upgrade pip
            pip install --no-cache-dir psycopg2-binary
            pip install --no-cache-dir -r requirements.txt
            pip install flake8 flake8-bugbear flake8-black

        - name: Flake8 Lint
          run: |
            make lint

        - name: Log in to Docker Hub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      

        - name: Build Docker image
          run: docker build -t "${{ secrets.DOCKER_USERNAME }}"/sre-bootcamp-api:1.0.0 .

        - name: Push Docker image
          run: docker push "${{ secrets.DOCKER_USERNAME }}"/sre-bootcamp-api:1.0.0